### ISSUE TITLE
Panel blank after clicking on location (500 internal error)

### ISSUE THREAD

**Issue by Nyazuma** [pluginsGLPI/treeview#23]
Hello,

I have GLPI 9.4.5 with plugins:
- Generic Object 2.8.0
- Treeview 1.8.1

After creating a custom object with the first plugin and adding few items in it.
I then tested Treeview plugin but nothing happen when clicking on the little + to expand, the panel goes blank. I have the locations but when clicking on locations to expand and look into it, it just crash/goes blank. I got an 500 internal error when looking in the browser console.
I don't understand what the problem is, if someone can help.

Thank you

**Comment by stonebuzz** [comment]
Hi @Nyazuma 

can you check log on server

- GLPI : /var/www/html/glpi/fiels/_log/
- Web server : /var/log/apache2 (or nginx) /

Can you give us more informations about your server configuration (apache / php / nginx etc ...)

Best regards

**Comment by Nyazuma** [comment]
Hello,

I'm running on Debian 10 with :
- Apache2 2.4.38
- PHP 7.3.14-1~deb10u1

Here you go for the error logs, no error logs related to treeview for /var/www/html/glpi/files/_log/php-errors.logs

Web server : /var/log/apache2/error.log :
> [Tue Mar 03 08:53:15.043720 2020] [php7:error] [pid 1002] [client 192.168.1.54:49246] PHP Fatal error:  Uncaught Error: Call to undefined method PluginGenericobjectCrossing::getObjectSearchOptions() in /var/www/html/glpi/plugins/genericobject/inc/object.class.php:113\nStack trace:\n#0 /var/www/html/glpi/inc/plugin.class.php(1162): PluginGenericobjectObject::getParentNodeSearchUrl(Array)\n#1 /var/www/html/glpi/plugins/treeview/inc/config.class.php(458): Plugin::doHookFunction('treeview_search...', Array)\n#2 /var/www/html/glpi/plugins/treeview/inc/config.class.php(301): PluginTreeviewConfig->getNodesFromDb()\n#3 /var/www/html/glpi/plugins/treeview/left.php(69): PluginTreeviewConfig->buildTreeview()\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/genericobject/inc/object.class.php on line 113, referer: http://192.168.1.54/glpi/plugins/treeview/left.php


Web server : /var/log/apache2/access.log :
> 192.168.1.54 - - [03/Mar/2020:08:53:10 +0100] "GET /glpi/ HTTP/1.1" 302 435 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/front/login.php HTTP/1.1" 302 436 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/front/central.php HTTP/1.1" 302 359 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/plugins/treeview/index.php HTTP/1.1" 200 874 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/css/print.css HTTP/1.1" 200 5378 "http://192.168.1.54/glpi/plugins/treeview/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/plugins/treeview/left.php HTTP/1.1" 200 1154 "http://192.168.1.54/glpi/plugins/treeview/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/plugins/treeview/pics/close.png HTTP/1.1" 200 661 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/plugins/treeview/css/dtree.css HTTP/1.1" 200 1154 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/css/jstree-glpi.min.css?v=9.4.5 HTTP/1.1" 200 4860 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/jqueryplugins/select2/css/select2.min.css?v=9.4.5 HTTP/1.1" 200 2325 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/jqueryplugins/qtip2/jquery.qtip.min.css?v=9.4.5 HTTP/1.1" 200 2170 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/font-awesome/css/all.min.css?v=9.4.5 HTTP/1.1" 200 11545 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/jqueryplugins/jquery-ui-timepicker-addon/jquery-ui-timepicker-addon.min.css?v=9.4.5 HTTP/1.1" 200 905 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/leaflet/plugins/Leaflet.markercluster/MarkerCluster.css?v=9.4.5 HTTP/1.1" 200 586 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/leaflet/plugins/Leaflet.markercluster/MarkerCluster.Default.css?v=9.4.5 HTTP/1.1" 200 730 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/leaflet/plugins/Leaflet.awesome-markers/leaflet.awesome-markers.css?v=9.4.5 HTTP/1.1" 200 931 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/leaflet/leaflet.css?v=9.4.5 HTTP/1.1" 200 3590 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/lib/leaflet/plugins/leaflet-control-osm-geocoder/Control.OSMGeocoder.css?v=9.4.5 HTTP/1.1" 200 627 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/lib/leaflet/plugins/Leaflet.fullscreen/leaflet.fullscreen.css?v=9.4.5 HTTP/1.1" 200 703 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/css/jquery-glpi.min.css?v=9.4.5 HTTP/1.1" 200 2353 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/css/print.min.css?v=9.4.5 HTTP/1.1" 200 4616 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/lib/jqueryplugins/fullcalendar/fullcalendar.print.min.css?v=9.4.5 HTTP/1.1" 200 993 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/fields/css/fields.min.css?v=1.10.3 HTTP/1.1" 200 562 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/genericobject/css/styles.min.css?v=2.8.0 HTTP/1.1" 200 607 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/treeview/css/treeview.min.css?v=1.8.1 HTTP/1.1" 200 1195 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/lib/jqueryplugins/fullcalendar/fullcalendar.min.css?v=9.4.5 HTTP/1.1" 200 3998 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/treeview/pics/base.ico HTTP/1.1" 200 4587 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/treeview/pics/plus.gif HTTP/1.1" 200 371 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/treeview/pics/folder.png HTTP/1.1" 200 3361 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:12 +0100] "GET /glpi/plugins/treeview/pics/plusbottom.gif HTTP/1.1" 200 370 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/front/central.php HTTP/1.1" 200 6615 "http://192.168.1.54/glpi/plugins/treeview/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/lib/leaflet/plugins/leaflet.spin/leaflet.spin.min.js?v=9.4.5 HTTP/1.1" 200 738 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/lib/jqueryplugins/select2/js/i18n/fr.js?v=9.4.5 HTTP/1.1" 200 816 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/lib/jqueryplugins/jquery-ui-timepicker-addon/i18n/jquery-ui-timepicker-fr.js?v=9.4.5 HTTP/1.1" 200 694 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/plugins/fields/js/drag-field-row.min.js?v=1.10.3 HTTP/1.1" 200 607 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/lib/jquery/i18n/jquery.ui.datepicker-fr.js?v=9.4.5 HTTP/1.1" 200 899 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/js/log_filters.min.js?v=9.4.5 HTTP/1.1" 200 655 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:11 +0100] "GET /glpi/front/css.php?file=main_styles&v=9.4.5 HTTP/1.1" 200 17245 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/lib/font-awesome/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 74141 "http://192.168.1.54/glpi/lib/font-awesome/css/all.min.css?v=9.4.5" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/pics/fd_logo.png HTTP/1.1" 200 2730 "http://192.168.1.54/glpi/front/css.php?file=main_styles&v=9.4.5" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/pics/menu_all.png HTTP/1.1" 200 579 "http://192.168.1.54/glpi/front/css.php?file=main_styles&v=9.4.5" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/pics/menu_config.png HTTP/1.1" 200 652 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/ajax/updatecurrenttab.php?itemtype=Central&id=0&tab=0 HTTP/1.1" 200 312 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/pics/spinner.48.gif HTTP/1.1" 200 27240 "http://192.168.1.54/glpi/front/css.php?file=main_styles&v=9.4.5" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:13 +0100] "GET /glpi/ajax/common.tabs.php?_target=/glpi/front/central.php&_itemtype=Central&_glpi_tab=Central$1&id=0 HTTP/1.1" 200 3972 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:14 +0100] "POST /glpi/ajax/planning.php HTTP/1.1" 200 321 "http://192.168.1.54/glpi/front/central.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.1.54 - - [03/Mar/2020:08:53:14 +0100] "GET /glpi/plugins/treeview/left.php?nodes=2.0&openedType= HTTP/1.1" 500 1941 "http://192.168.1.54/glpi/plugins/treeview/left.php" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
::1 - - [03/Mar/2020:08:53:18 +0100] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
::1 - - [03/Mar/2020:08:53:19 +0100] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"
::1 - - [03/Mar/2020:08:53:20 +0100] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) (internal dummy connection)"

Thank you

**Comment by stonebuzz** [comment]
@Nyazuma 
Can you retry with latest version (glpi and plugin)

Best regards
